services:
  db:
    image: postgres:16
    container_name: stockdb
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
    ports:
      - "5432:5432"
    volumes:
      - stockdb_data:/var/lib/postgresql/data

volumes:
  stockdb_data:
